In [1]:
import numpy as np

In [2]:
a = np.loadtxt('test_W.txt')

In [3]:
a

array([[ 1.,  2.,  1.,  1., 11.],
       [ 1.,  2.,  1.,  2., 12.],
       [ 1.,  2.,  2.,  1., 13.],
       [ 1.,  2.,  2.,  2., 14.],
       [ 1.,  3.,  1.,  1., 15.],
       [ 1.,  3.,  1.,  2., 16.],
       [ 1.,  3.,  2.,  1., 17.],
       [ 1.,  3.,  2.,  2., 18.],
       [ 2.,  3.,  1.,  1., 19.],
       [ 2.,  3.,  1.,  2., 20.],
       [ 2.,  3.,  2.,  1., 21.],
       [ 2.,  3.,  2.,  2., 22.]])

In [4]:
i = a[:,0].astype(int)
print(i)

[1 1 1 1 1 1 1 1 2 2 2 2]


In [5]:
j = a[:,1].astype(int)
print(j)

[2 2 2 2 3 3 3 3 3 3 3 3]


In [6]:
k = a[:,2].astype(int)
print(k)

[1 1 2 2 1 1 2 2 1 1 2 2]


In [7]:
l = a[:,3].astype(int)
print(l)

[1 2 1 2 1 2 1 2 1 2 1 2]


In [8]:
b = a[:,4]
print(b)

[11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22.]


In [9]:
# number of position
n = j.max()
print(n)

3


In [10]:
# number of value at each position
m = k.max()
print(m)

2


In [11]:
c = np.zeros((n*m,n*m))

In [12]:
for ii in range(i.shape[0]):    
    i1 = (i[ii]-1)*m + (k[ii]-1)   # i[ii]-1 : converted matlab index to pytho
    j1 = (j[ii]-1)*m + (l[ii]-1)
    c[i1,j1] = b[ii]
    c[j1,i1] = b[ii]
    
print(c)

[[ 0.  0. 11. 12. 15. 16.]
 [ 0.  0. 13. 14. 17. 18.]
 [11. 13.  0.  0. 19. 20.]
 [12. 14.  0.  0. 21. 22.]
 [15. 17. 19. 21.  0.  0.]
 [16. 18. 20. 22.  0.  0.]]


In [13]:
np.savetxt('test_w_converted.dat',c,fmt='% f')